spring:
  datasource:
    url: jdbc:postgresql://localhost:3308/hrms
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    view:
      prefix: /views/
      suffix: .jsp